# Generated by Django 3.2.8 on 2021-10-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nafar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='nafar',
        ),
    ]
