# Generated by Django 3.2.8 on 2021-10-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nafar', '0002_rename_user_profile_nafar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nafar',
            new_name='user',
        ),
    ]
